dubbo:
  application:
    name: dubbo-item
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.b2b.dubbo.search.service
  protocol:
    name: dubbo
    port: '20886'

spring:
  data:
    solr:
      host: http://localhost:8983/solr/collection1
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trusted: true
      trust-all: true
    pool:
      enabled: false
      max-connections: 50
      idle-timeout: 30000