dubbo:
  application:
    name: dubbo-item
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.b2b.dubbo.item.service
  protocol:
    name: dubbo
    port: '20883' #默认port:20880，项目多模块时候就导致端口冲突。''是重点哦

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trusted: true
      trust-all: true
    pool:
      enabled: false
      max-connections: 50
      idle-timeout: 30000